author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
 Home: /
#  Series: /series/
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
#  About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set utterances, gitment, uyan or disqus
comment: gitment

# utterances config
utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: AsukaD
gitment_repo: AsukaD.github.io
gitment_oauth_id: cef79e8c7228ad95f47f
gitment_oauth_secret: db9c4314da6ceaafa30127213a59327ebb854718

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: https://avatars.githubusercontent.com/u/43928593?s=400&u=0cfdc440c53d262310b10ec1572eb5190474b2a8&v=4
  description: 
  weibo_username: 
  twitter_username: 
  github_username: AsukaD
  zhihu_username: 
  douban_username: 
  linkedin_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

# China Registration
# e.g. 京ICP备12345678号-1
icp:
  enable: false
  number: 京ICP备12345678号-1 # e.g. 京ICP备12345678号-1
# e.g. 京公网安备 12345678901234号
ga:
  enable: false
  province: 京           # e.g. 京
  number: 12345678901234 # e.g. 12345678901234

